### ISSUE TITLE
images with white background

### ISSUE THREAD

**Issue by jaydubal** [iluvgirlswithglasses/FingerprintRecognitionV2#2]
Hi,

For images with white background, the MinutiaeExtractor.ExtractAndExport generates an invalid .inp file, with one or more lines, having just one array element instead of three. Which would later throw exception in Fingerprint constructor's Minutiae.Add code. 

Inverting the image fixes it.

Image<Gray, byte> dest = new Image<Gray, byte>(src.Width, src.Height);
CvInvoke.BitwiseNot(src, dest);

Maybe you can change the code to incorporate, white background images.

Thanks!

**Comment by iluvgirlswithglasses** [comment]
You can fix this by editing `Util/Preprocessing/Normalization.cs` at line 38-43. The original program is implemented like this:

```C#
static private double NormalizePixel(double px, double avg, double std)
{
    double coeff = Abs(px - avg) / std;
    // flip fg/bg color here
    if (px < avg) 
        return coeff;   // positive --> background
    return -coeff;      // negative --> foreground
}
```

Just change it to match your need:
```C#
static private double NormalizePixel(double px, double avg, double std)
{
    double coeff = Abs(px - avg) / std;
    if (px < avg) 
        return -coeff;   // negative --> foreground
    return +coeff;      // positive --> background
}
```

**Comment by jaydubal** [comment]
Thanks!
