### ISSUE TITLE
Best way to match (1:n)

### ISSUE THREAD

**Issue by jaydubal** [iluvgirlswithglasses/FingerprintRecognitionV2#3]
How to match or recognize current finger print with all avaliable existing ones (n)? 
should all "*.inp" files be looped?

Please suggest. Thanks!

**Comment by iluvgirlswithglasses** [comment]
Assume that you want to match a fingerprint (called "fingerprint A") with a set of $N$ fingerprints, do as following:

Firsly, build the program via `dotnet build`

Then, extract .inp files from the set of $N$ fingerprint, save them to another folder:
`bash run extract <threads count> <fingerprints set directory> <.inp files directory>`

Finally, call the `match 1-n` function:
`bash run match-1n <threads count> <fingerprint A.png> <fingerprints set directory> <.inp files directory> <output.png>`

The command line interface of this program is not yet completed so its kinda hard to make things work. I'll finish them later.

**Comment by jaydubal** [comment]
Thanks!
